# Generated by Django 5.0.7 on 2024-08-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpeg', upload_to='')),
                ('title', models.CharField(default='Ads', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, default=0, null=True)),
                ('phone', models.CharField(default='113631232', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Networking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_image', models.ImageField(default='default.jpeg', upload_to='')),
                ('title', models.CharField(default='Adds', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
