# Generated by Django 5.0.7 on 2024-08-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('club_description', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(default='113631232', max_length=9)),
                ('officials_name', models.CharField(default='8Tech', max_length=100)),
            ],
        ),
    ]
