# Generated by Django 5.0.7 on 2024-08-06 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HouseDatails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='House Images', max_length=100)),
                ('images', models.ImageField(default='default.jpeg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_image', models.ImageField(default='default.jpeg', upload_to='')),
                ('house_name', models.CharField(max_length=100)),
                ('house_type', models.CharField(blank=True, max_length=100, null=True)),
                ('rent', models.IntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('available_rooms', models.IntegerField(default=0)),
                ('phone', models.CharField(default='113631232', max_length=9)),
                ('houseDetails', models.ManyToManyField(blank=True, to='housing.housedatails')),
            ],
        ),
    ]
